server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

spring:
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_MAX_POOL_SIZE}
      minimum-idle: ${SPRING_DATASOURCE_MIN_IDLE}
      idle-timeout: ${SPRING_DATASOURCE_IDLE_TIMEOUT}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_HIBERNATE_DIALECT}
        jdbc.time_zone: ${SPRING_JPA_TIMEZONE}
        default_schema: ${SPRING_JPA_DEFAULT_SCHEMA}

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: ${JWT_VALID_DURATION}
  refreshable-duration: ${JWT_REFRESHABLE_DURATION}

config:
  allowed-origin: ${CONFIG_ALLOWED_ORIGIN}

app:
  seed-admin: ${APP_SEED_ADMIN}
